about/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('/', views.home)
    

]

activity/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.activity_view, name='activity'),
    path('create/attendee/<str:name>', views.attendee_create_view, name="add_attendee"),
    path('create/activity/', views.activity_create_view, name="create_activity"),
    path('delete/<str:nama>', views.activity_delete_view, name="delete"),
]

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('home/', views.index),
    path('about/', views.about),
    path('time/', views.time),
    path('time/<int:id>', views.time_mod),


]

matkul/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.matkul_create_view),
    path('detail/', views.matkul_list_view),
    path('delete/<str:nama>', views.matkul_delete_view, name="delete"),
    path('detail/<str:nama>', views.matkul_detail_view, name="detail"),
]

websiteproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('matkul/', include('matkul.urls')),
    path('activity/', include('activity.urls')),
]

about/models.py
from django.db import models

# Create your models here.

activity/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

class Attendee(models.Model):
    activity_name = models.ForeignKey(Activity, on_delete= models.CASCADE,null=True, blank=True)
    nickname = models.CharField(max_length=20, unique=True)
    fullname = models.CharField(max_length=60)
    id_line = models.CharField(max_length=20)

    def __str__(self):
        return self.nickname

home/models.py
from django.db import models

matkul/models.py
from django.db import models
import datetime as dt
from datetime import timedelta

# Create your models here.
SEMESTER = (('GASAL', 'Gasal'),
            ('GENAP 2', 'Genap'),
            )
TAHUN = (('2019/2020','2019/2020'),
         ('2020/2021','2020/2021'),
         ('2021/2022','2021/2022'),
         ('2022/2023','2022/2023'),
         ('2023/2024','2023/2024'),
         ('2024/2025','2024/2025'),

)


class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=100, unique=True)
    dosen_pengajar = models.CharField(max_length=120)
    jumlah_sks = models.PositiveSmallIntegerField()
    deskripsi_matkul = models.TextField(blank=True, null=True)
    semester = models.CharField(max_length=10,choices=SEMESTER, default='Genap')
    tahun_ajaran = models.CharField(max_length=10,choices=TAHUN, default= '2019/2020')
    ruang_kelas = models.CharField(max_length=30)

    def __str__(self):
        return self.nama_matkul

class Tugas(models.Model):
    matkul = models.ForeignKey(Matkul, on_delete=models.CASCADE)
    tugas = models.TextField(max_length=120)
    deadline = models.DateTimeField()

    def __str__(self):
        return self.tugas

activity/forms.py
from django import forms

from .models import Activity, Attendee

class ActivityForm(forms.ModelForm):

    class Meta:
        model = Activity
        fields = [
            'title',
        ]

class AttendeeForm(forms.ModelForm):

    class Meta:
        model = Attendee
        fields = [
            'activity_name',
            'nickname',
            'fullname',
            'id_line',

        ]

matkul/forms.py
from django import forms

from .models import Matkul

class MatkulForm(forms.ModelForm):

    class Meta:
        model = Matkul
        fields = [
            'nama_matkul',
            'dosen_pengajar',
            'jumlah_sks',
            'deskripsi_matkul',
            'semester',
            'tahun_ajaran',
            'ruang_kelas',
            

        ]

about/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index (request):
    return render(request, 'about.html')

def home(request):
    return render(request, 'home.html')

activity/views.py
from django.shortcuts import render, get_object_or_404

from .forms import ActivityForm, AttendeeForm
from .models import Activity, Attendee

# Create your views here.

def activity_view(request):
    activities = Activity.objects.all()
    context = {
        'activities' : activities,
    }
    return render(request, 'activity_view.html', context)

def attendee_create_view(request, name):
    form = AttendeeForm(request.POST or None)
    if form.is_valid():
        x = form.save(commit=False)
        x.activity_name = Activity.objects.get(title = name)
        x.save()
        form = AttendeeForm()

    context = {
        'form' : form,
    }
    return render(request, 'attendee_create.html', context)

def activity_create_view(request):
    form = ActivityForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ActivityForm()

    context = {
        'form':form,
    }
    return render(request, 'activity_create.html', context )

def activity_delete_view(request,nama=None):
    activities = Activity.objects.all()
    obj = get_object_or_404(Attendee, nickname=nama)
    if request.method == 'POST':
        obj.delete()

    context = {
        'activities':activities,
    }
    return render(request, 'activity_view.html', context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

import datetime
from django.utils import timezone as tz
from datetime import timedelta

# -*- coding: utf-8 -*-


from django.shortcuts import render

# Import Datetime
from datetime import datetime

# Create your views here.
def index (request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')


def time(request):
    args = {}
    now = tz.now()
    args['sekarang'] = now
    return render(request, 'time.html', args)

def time_mod(request, id):
    args={}
    now = tz.now()
    waktu = now + timedelta(hours=id)

    args['sekarang'] = waktu
    return render(request, 'time.html', args)

matkul/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
import datetime
from .forms import MatkulForm
from .models import Matkul, Tugas
from django.db.models import Q
from datetime import timedelta

def matkul_create_view(request):
    form = MatkulForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = MatkulForm()

    context = {
        'form' : form,
    }
    return render(request, "matkul_create.html", context)

def matkul_list_view(request):
    obj = Matkul.objects.all()
    
    context = {
        'object' : obj
    }
    return render(request, "matkul_list.html", context)

def matkul_delete_view(request,nama=None):
    temp = get_object_or_404(Matkul, nama_matkul=nama)
    obj = get_object_or_404(Matkul, nama_matkul=nama)
    if request.method == 'POST' or 'GET':
        obj.delete()

    context = {
        "temp" : temp ,
        "object" : obj,

    }
    return render(request, 'matkul_delete.html', context)

def matkul_detail_view(request, nama):
    obj = Matkul.objects.get(nama_matkul = nama)
    now = datetime.datetime.now()
    tugasnya = Tugas.objects.filter(matkul = obj).order_by('deadline').reverse()
    tgs_gte_deadline = Tugas.objects.filter(matkul = obj).order_by('deadline').reverse().filter(Q(deadline__gte=now)|Q(deadline=None))
    tgs_lt_deadline = Tugas.objects.filter(matkul = obj).order_by('deadline').reverse().filter(Q(deadline__lt=now))

    context = {
        'object': obj,
        'tugasnya' : tugasnya,
        'tugas_gte_deadline' : tgs_gte_deadline,
        'tugas_lt_deadline' : tgs_lt_deadline,
        'now' : now,
        
    }
    return render(request, 'matkul_detail.html', context)

about/templates/about.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>About Me</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="../static/styles-about.css">

  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>

  <section id="title">

    <div class="container-fluid" >
    <nav class="navbar navbar-expand-lg navbar-light ">
      <a class="navbar-brand" href="/">Hugo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/time">Time</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/matkul">Mata Kuliah</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/activity">Activity</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#footer">Contact</a>
              </li>
          </ul>

      </div>

  </nav>

<!-- Head  -->

    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6" >
      <h1 id="head-text" style="padding-top: 0%;font-size: 6vw;" >Hi! I’m Hugo.
        I like to learn new things.</h1>
      
      <!-- Button trigger modal -->
      <button style="margin:0.4em auto;" type="button" id="activities-button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        See my activities
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Here is my lastest activities</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="../static/images/friends-wedding.jpg" alt="Third slide">
                    <p>9 February 2020, me and my mom went to my friends's son wedding</p>
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="../static/images/with-my-friends.jpg" alt="Second slide">
                    <p>30 January 2020, me and my friends went to Kintan-Buffet immediately just to get a student promo</p>
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="../static/images/grandma-birthday.jpg" alt="First slide">
                    <p>26 January 2020, I visited my grandma's house to celebrate her 84th birthday</p>
                  </div>


                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="col-lg-6 col-md-6 col-sm-6">
      <picture>
      <img class="head-image" style="margin-left: 0%; padding-bottom: 5%;" src="../static/images/hugo_camp.jpg" alt="">
      </picture>
    </div>
  </div>

</div>
  </section>


  <!-- Description -->

  <section id="description">
    <div class="row">
      <div class="col-lg-6 col-md-12 col-sm-12" >
        <img class="rounded-circle img-fasilkom" style="min-height:20vh;" src="../static/images/fasilkom_ui.jpg" alt="">
      </div>
      <div class="col-lg-6 col-md-12 col-sm-12 description-text">
        <h2>Who Am I</h2>
        <p style="font-size: x-large;">I’m a Computer Science student at University of Indonesia. Right now, I’m in my first year college, still trying to adapt with the all new courses in my faculty, but lucky me, I got a good friends that support me well. My focuses now is on Machine Learning escpecially on Deep Learning yet I still exploring other concentration areas of computer science.</p>
      </div>
    </div>

  </section>

  <section id="hobbies">
    <div class="hobbies-title">
      <h2>Here is my hobbies</h2>
    </div>
    <div class="hobbies-text"> 

    </div>

    <div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class=" embed-responsive embed-responsive-4by3 hobbies-videos ">
            <video controls class="embed-responsive-item hobbies-videos" src="../static/videos/karaoke_with_friends.mp4"></video>
          </div>
          <p>This is me sang together with my good friends.</p>
        </div>
        <div class="carousel-item">
          <div class=" embed-responsive embed-responsive-4by3 hobbies-videos">
            <video controls class="embed-responsive-item" src="../static/videos/hugo_berenang.mp4"></video>
          </div>
          <p>Me on 2017, recorded my amateur breaststroke move.</p>
        </div>
        <div class="carousel-item">
          <div class=" embed-responsive embed-responsive-4by3 hobbies-videos">
            <video controls class="embed-responsive-item" src="../static/videos/hugo_breakdance.mp4"></video>
          </div>
          <p>Me trying to do a simple windmill on friend’s 17th birthday party.</p>
        </div>
      </div>
      <a class="carousel-control-prev wkw" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    </div>
  </section> 




  <section id="feedback">
  <h2 class="feedback-title">Feedback</h2>

  <form>
    <div class="form-group row">
      <label for="inputname3" class="col-sm-2 col-form-label">Name</label>
      <div class="col-sm-10">
        <input type="name" class="form-control" id="inputname3" placeholder="Name">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
      </div>
    </div>

    <div class="form-group">
      <label for="FormControlTextarea1">Comments</label>
      <textarea class="form-control" id="FormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>

    
  </form>
</section>

<footer id="footer">
  <a href="https://www.facebook.com/profile.php?id=100008717070578"><i class="social-icon fab fa-facebook-square"></i></a>
  <a href="https://www.linkedin.com/in/hugo-irwanto-bba220195/?originalSubdomain=id"><i class="social-icon fab fa-linkedin"></i></a>
  <a href="https://www.instagram.com/hugoirrr/?hl=id"><i class="social-icon fab fa-instagram"></i></a>
  <p>© Copyright 2020 Hugo Irwanto</p>

</footer>


</body>

</html>

activity/templates/activity_create.html
{% load crispy_forms_tags %}

<style>
    .container-body {
        padding: 7% 15%;
    }
</style>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gabung kuy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body class="container-body">

    <h1>Nama kegiatan</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <ul>title : {{form.title}}</ul>
        <button type="submit" class="btn btn-success" >submit</button>
    </form>
    
</body>
</html>

activity/templates/activity_view.html
<style>
    .container-body {
    padding: 7% 15%;
    }
    .card-body {
        text-align: center;
        
    }
    .card-name {
        text-align: justify;
    }
    .card-button {
        margin-top: 10%;
    
    }

</style>

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activities</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body class="container-body">



  <nav class="navbar navbar-expand-lg fixed-top navbar-light ">
    <div class="container-fluid" id="s">
      <a class="navbar-brand" href="/">Hugo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link" href="/time">Time</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/matkul">Mata Kuliah</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/activity">Activity</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/#footer">Contact</a>
              </li>
          </ul>

        </div>
    </div>

  </nav>


 <form method="POST" action="{% url 'create_activity'%}">
  {% csrf_token %}
<button type="create" class="btn btn-primary card-button" >Create</button>
</form>
    <div class="row">
    {% for i in activities %}
        
        <div class="col-lg-4 col-md-4 col-sm-6">
      <div class="card w-100">
        <div class="card-body">
          <h5 class="card-title">{{i}}</h5>
          <h6 class="card-name">nama</h6>
          {% for j in i.attendee_set.all %}
          <div class="row">
          <div class="col"><li class ='card-name'>{{j.nickname}}</li></div>
          <div class="col">
            <div class="float-right">
          <form method="POST" action="{% url 'delete' j.nickname %}">
            {% csrf_token %}
            <button class="tombol">&times;</button>
          </form>
        </div>
        </div>
          </div>

          {% endfor %}
          <form method="POST" action="{% url 'add_attendee' i %}">
            {% csrf_token %}
          <button type="join" class="btn btn-primary card-button" >Join kuy</button>
          </form>
          <!-- <a data-target="#form" class="btn btn-primary card-button">Join kuy</a> -->
        </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div id="form">
        {{form.as_p}}
    </div>

    </body>
</html>

activity/templates/attendee_create.html
{% load crispy_forms_tags %}

<style>
    .container-body {
        padding: 7% 15%;
    }

    .baris {
        padding-bottom: 5%;
    }
</style>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gabung kuy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body class="container-body">

    <h1>Join</h1>

    <form method="POST" >
        {% csrf_token %}

        <div class="row baris">
            <div class="col-12">
                Nickname : {{form.nickname}}
            </div>
        </div>
        <div class="row baris">
            <div class="col-12">
               Fullname : {{form.fullname}}
            </div>
        </div>
        <div class="row baris">
            <div class="col-12">
               id_line : {{form.id_line}}
            </div>
        </div>
<div class="row">
    <div class="col-6">
        <button type="submit" class="btn btn-success" >submit</button>
    </form>
</div>

    <div class="col-6">
        <form action="/activity/">
            <button class="btn btn-success">kembali</button>
        </form>
    </div>
</div>
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hugo's Website</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="../static/styles-home.css"> -->
    <link href="{% static 'home.css' %}" rel="stylesheet">
  
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    {% block section %} {% endblock %}

    <section id="feedback">
      <h2 class="feedback-title">Feedback</h2>
      
      <form>
        <div class="form-group row">
          <label for="inputname3" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <input type="name" class="form-control" id="inputname3" placeholder="Name">
          </div>
        </div>
    
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
          <div class="col-sm-10">
            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
          </div>
        </div>
    
        <div class="form-group">
          <label for="FormControlTextarea1">Comments</label>
          <textarea class="form-control" id="FormControlTextarea1" rows="3"></textarea>
        </div>
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
    
        
      </form>
    </section>
    
    <footer id="footer">
      <a href="https://www.facebook.com/profile.php?id=100008717070578"><i class="social-icon fab fa-facebook-square"></i></a>
      <a href="https://www.linkedin.com/in/hugo-irwanto-bba220195/?originalSubdomain=id"><i class="social-icon fab fa-linkedin"></i></a>
      <a href="https://www.instagram.com/hugoirrr/?hl=id"><i class="social-icon fab fa-instagram"></i></a>
      <p>© Copyright 2020 Hugo Irwanto</p>
    
    </footer>
</body>
</html>